/////////EXPERIENCE REDUCER TYPES//////////////
export const CLEAR_STATE = 'CLEAR_STATE'
export const SET_MODAL_CREATESHOW = 'SET_MODAL_CREATESHOW'
export const SET_LINK_PROJECT = 'SET_LINK_PROJECT'
export const SET_MODAL_SHOW = 'SET_MODAL_SHOW'
export const SET_PROJECTS = 'SET_PROJECTS'
export const SET_NAME_PROJECT = 'SET_NAME_PROJECT'
